### PR TITLE
Encountered error C1083: Cannot open include file: 'winrt/Microsoft.U…

### PR DESCRIPTION
**Pull request by Cornflakes-code**
In PDFFilePageSource.cpp I encountered error C1083: Cannot open include file: 'winrt/Microsoft.UI.Dispatching.h': No such file or directory

Apparently:
When updating (winrt) from 0.8.0 preview to 0.8.0 there was a namespace change from Microsoft.System to Microsoft.UI.Dispatching and resume_foreground is now defined in Microsoft.UI.Dispatching.co_await.h.

Note that accepting this pull request may require winrt to be upgraded.

### CODE REVIEW

**Review by fredemmott — COMMENTED** [review]
Thanks! I'm not sure what's going on here: OpenKneeboard [always builds with C++/WinRT 2.0.230706.1](https://github.com/OpenKneeboard/OpenKneeboard/blob/68b1c13d466ef7ec3c990299185adca0d1175ca6/third-party/cppwinrt.cmake#L4)

C++/WinRT 2.0.230706.1 generates the dispatching header file as part of OpenKneeboard's build:

```
build/src/app/app-common/OpenKneeboard-App-Common.dir/Debug/Generated Files/winrt/impl/Microsoft.UI.Dispatching.0.h
build/src/app/app-common/OpenKneeboard-App-Common.dir/Debug/Generated Files/winrt/impl/Microsoft.UI.Dispatching.1.h
build/src/app/app-common/OpenKneeboard-App-Common.dir/Debug/Generated Files/winrt/impl/Microsoft.UI.Dispatching.2.h
build/src/app/app-common/OpenKneeboard-App-Common.dir/Debug/Generated Files/winrt/Microsoft.UI.Dispatching.h
```
How are you building this file, and on what architecture?

If this generation fails, I'd expect OpenKneeboard's cmake to fail, but if not, the Windows SDK (which is different to the Windows App SDK) includes an obsolete version of C++/WinRT; if for some reason C++/WinRT generation fails, and CMake does not detect a failure, the compiler may pick up the old version and headers from the Windows SDK.

**Comment by fredemmott** [comment]
While C++/WinRT isn't in OpenKneeboard-App-Common's direct dependency list, it should be inherted from https://github.com/OpenKneeboard/OpenKneeboard/blob/68b1c13d466ef7ec3c990299185adca0d1175ca6/src/CMakeLists.txt#L32

If in a completely empty build directory, I run `cmake ..; cmake --build . --config Debug --target OpenKneeboard-App-Common`, it does successfully build this target, including downloading and building the new C++/WinRT version.

This is using cmake version 3.26.4-msvc4 which is included in Visual Studio 2022 17.7.4; I'll update to 17.8.2

**Comment by Cornflakes-code** [comment]
Leave it with me. I may well have messed up the winrt include path.

**Comment by fredemmott** [comment]
Sure, thanks again :) Just to confirm, I upgraded VS2022 to v17.8.2 and both the individual target and OpenKneeboard as a whole build fine

**Comment by fredemmott** [comment]
Closing, seems to be a local issue.
